name: Windows build

on:
  push:
    branches:
      - deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{ secrets.GH_PAT }}

      - uses: kuhnroyal/flutter-fvm-config-action@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: pub get
        run: flutter pub get

      - run: flutter build windows --release
      - name: Download VC++ redistributable
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "vc_redist.x64.exe"
      - name: Install VC++ redistributable
        run: |
          .\vc_redist.x64.exe /install /quiet /norestart

      - name: Copy required VC++ runtime DLLs
        run: |
          $dest = "$(Get-Location)\build\windows\runner\Release"
          if (-Not (Test-Path $dest)) {
            New-Item -ItemType Directory -Path $dest -Force | Out-Null
          }
          Copy-Item "C:\Windows\System32\MSVCP140.dll" $dest
          Copy-Item "C:\Windows\System32\VCRUNTIME140.dll" $dest
          Copy-Item "C:\Windows\System32\VCRUNTIME140_1.dll" $dest
          if (Test-Path "C:\Windows\System32\CONCRT140.dll") {
            Copy-Item "C:\Windows\System32\CONCRT140.dll" $dest
          }

      - uses: actions/upload-artifact@v4
        with:
          name: k8090_controller
          path: build/windows
